### ISSUE TITLE
Tried on pale moon

### ISSUE THREAD

**Issue by delicacy1** [manandhar/no-age-limit#1]
i even changed the application id in the rdf file, this addon seems to not work anymore, it's strange cause it was recently added..

**Comment by manandhar** [comment]
Its an compatibility issue,
"Pale Moon also allows Firefox extensions to be installed, as long as these extensions are compatible with version 24 of Firefox."
The add-on was created using jpm, its only compatible with firefox version 38 or higher.

 If you need to work with earlier versions of Firefox, you'll need to use the old cfx tool.

sources: 

- https://developer.mozilla.org/en-US/Add-ons/SDK/Tutorials/Getting_Started_%28jpm%29
- https://www.palemoon.org/faq.shtml#Why_do_some_add-ons_not_work
